name: Deploy Library Microservice

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main  # Restrict deployments to the main branch
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_LOG: DEBUG  # Enable detailed logs for Terraform
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true

    steps:
      # Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Azure Login Step
      - name: Azure Login
        uses: azure/login@v1.4.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Set up Terraform CLI
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      
      - name: Set execute permissions
        run: chmod +x ./scripts/*.sh

      # Terraform Init to initialize working directory
      - name: Terraform Init
        run: terraform init

      - name: Export Environment Variables for Terraform
        run: |
          echo "TF_VAR_ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "TF_VAR_ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}" >> $GITHUB_ENV

      - name: Terraform Plan to generate and capture the infrastructure plan
        id: tf_plan
        run: terraform plan -out=tfplan -var="ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}" -var="ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}" -var="ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}" -var="ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}"
        continue-on-error: false  # Fails if the plan encounters an error

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Retrieve AKS credentials
        run: |
          az aks get-credentials --resource-group deakinuni --name librarypart05withterraform --overwrite-existing
          cat ~/.kube/config | base64 | tr -d '\n' > kubeconfig.txt
          echo "KUBECONFIG:"
          cat kubeconfig.txt

      - name: Set KUBE_CONFIG environment variable
        run: |
          echo "KUBE_CONFIG=$(cat kubeconfig.txt)" >> $GITHUB_ENV

      # Install kubectl and configure access to Kubernetes cluster
      - name: Install kubectl and Configure Cluster Access
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ env.KUBE_CONFIG }}
          kubectl-version: v1.30.2


      # Verify Kubernetes API access
      - name: Check Kubernetes Cluster Status
        run: kubectl cluster-info
        continue-on-error: false  # Fails if cluster info can't be fetched

      # Capture Terraform Outputs
      - name: Capture Terraform Outputs
        id: tf_output
        run: |
          echo "CONTAINER_REGISTRY=$(terraform output -raw registry_login_server)" >> $GITHUB_ENV
          echo "REGISTRY_UN=$(terraform output -raw registry_username)" >> $GITHUB_ENV
          echo "REGISTRY_PW=$(terraform output -raw registry_password)" >> $GITHUB_ENV
        continue-on-error: false  # Fails if output capture fails

      # Set environment variables dynamically from GitHub Secrets
      #- name: Set Container Registry Environment Variables
      #  run: |
      #    echo "Setting container registry environment variables..."
      #    echo "CONTAINER_REGISTRY=${{ secrets.CONTAINER_REGISTRY }}" >> $GITHUB_ENV
      #    echo "REGISTRY_UN=${{ secrets.REGISTRY_UN }}" >> $GITHUB_ENV
      #    echo "REGISTRY_PW=${{ secrets.REGISTRY_PW }}" >> $GITHUB_ENV

      - name: Debug container registry environment variable
        run: echo "CONTAINER_REGISTRY is $CONTAINER_REGISTRY"

      - name: Log in to Azure Container Registry
        run: |
          az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}
          az account show
          az acr login --name $CONTAINER_REGISTRY

      # Build the Docker image
      - name: Build Docker Image
        run: ./scripts/build-image.sh
        continue-on-error: false  # Fails if the build process fails

      # Publish the Docker image to the container registry
      - name: Publish Docker Image
        run: ./scripts/push-image.sh
        continue-on-error: false  # Fails if the push fails

      - name: Delay for 30 seconds
        run: sleep 10
      
      # Attach ACR to AKS
      - name: Attach ACR to AKS
        run: |
          AKS_NODE_RG=$(az aks show --resource-group deakinuni --name librarypart05withterraform --query nodeResourceGroup -o tsv)
          az aks update -n librarypart05withterraform -g $AKS_NODE_RG --attach-acr librarypart05withterraform


      # Deploy the microservice to Kubernetes
      - name: Deploy Microservice
        run: ./scripts/deploy.sh
        continue-on-error: false  # Fails if the deployment fails

      # Optional: Cleanup (commented out, can be used if needed)
      #- name: Delete resources
      #  run: ./scripts/delete.sh
